@extends('layouts.app')

@section('title', ($customer->exists ? 'Edit Customer' : 'Add Customer').' | Casa Paraiso Spa Management System')
@section('page_title', $customer->exists ? 'Edit Customer Profile' : 'Add Customer Profile')
@section('page_description', 'Maintain a linked customer account or create a standalone walk-in customer record.')

@section('content')
    <div class="mb-6"><a href="{{ route('management.customers.index') }}" class="text-sm font-medium text-zinc-600 hover:text-zinc-950">Back to customers</a></div>
    <form method="POST" action="{{ $customer->exists ? route('management.customers.update', $customer) : route('management.customers.store') }}" class="mx-auto max-w-4xl space-y-6 rounded-lg border border-zinc-200 bg-white p-6 shadow-sm">
        @csrf
        @if ($customer->exists) @method('PUT') @endif
        <div class="grid gap-6 sm:grid-cols-2">
            <div class="sm:col-span-2">
                <label for="user_id" class="block text-sm font-medium text-zinc-700">Linked customer account</label>
                <select id="user_id" name="user_id" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><option value="">No linked account (walk-in)</option>@foreach ($users as $user)<option value="{{ $user->id }}" @selected((string) old('user_id', $customer->user_id) === (string) $user->id)>{{ $user->name }} ({{ $user->email }})</option>@endforeach</select>
                <p class="mt-1 text-xs text-zinc-500">Only customer-role accounts without another profile are available.</p>
                @error('user_id') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror
            </div>
            <div><label for="first_name" class="block text-sm font-medium text-zinc-700">First name</label><input id="first_name" name="first_name" value="{{ old('first_name', $customer->first_name) }}" required class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('first_name') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="last_name" class="block text-sm font-medium text-zinc-700">Last name</label><input id="last_name" name="last_name" value="{{ old('last_name', $customer->last_name) }}" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('last_name') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="email" class="block text-sm font-medium text-zinc-700">Email</label><input id="email" name="email" type="email" value="{{ old('email', $customer->email) }}" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('email') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="phone" class="block text-sm font-medium text-zinc-700">Phone</label><input id="phone" name="phone" value="{{ old('phone', $customer->phone) }}" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('phone') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="birth_date" class="block text-sm font-medium text-zinc-700">Birth date</label><input id="birth_date" name="birth_date" type="date" max="{{ now()->format('Y-m-d') }}" value="{{ old('birth_date', $customer->birth_date?->format('Y-m-d')) }}" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('birth_date') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="gender" class="block text-sm font-medium text-zinc-700">Gender</label><select id="gender" name="gender" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><option value="">Prefer not to specify</option><option value="female" @selected(old('gender', $customer->gender) === 'female')>Female</option><option value="male" @selected(old('gender', $customer->gender) === 'male')>Male</option><option value="other" @selected(old('gender', $customer->gender) === 'other')>Other</option><option value="prefer_not_to_say" @selected(old('gender', $customer->gender) === 'prefer_not_to_say')>Prefer not to say</option></select>@error('gender') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="is_active" class="block text-sm font-medium text-zinc-700">Status</label><select id="is_active" name="is_active" required class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><option value="1" @selected((string) old('is_active', (int) ($customer->exists ? $customer->is_active : true)) === '1')>Active</option><option value="0" @selected((string) old('is_active', (int) $customer->is_active) === '0')>Inactive</option></select>@error('is_active') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div class="sm:col-span-2"><label for="address" class="block text-sm font-medium text-zinc-700">Address</label><textarea id="address" name="address" rows="3" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">{{ old('address', $customer->address) }}</textarea>@error('address') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div class="sm:col-span-2"><label for="notes" class="block text-sm font-medium text-zinc-700">Notes</label><textarea id="notes" name="notes" rows="4" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">{{ old('notes', $customer->notes) }}</textarea>@error('notes') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
        </div>
        <div class="flex justify-end gap-3 border-t border-zinc-200 pt-5"><a href="{{ route('management.customers.index') }}" class="rounded-md border border-zinc-300 px-4 py-2 text-sm font-semibold text-zinc-700 hover:bg-zinc-50">Cancel</a><button class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-800">{{ $customer->exists ? 'Save changes' : 'Create customer' }}</button></div>
    </form>
@endsection
