@extends('layouts.app')

@section('title', ($availability->exists ? 'Edit Availability' : 'Add Availability').' | Casa Paraiso Spa Management System')
@section('page_title', $availability->exists ? 'Edit Availability' : 'Add Availability')
@section('page_description', 'Choose either a recurring weekday or one specific date, then set the therapist working window.')

@section('content')
    <div class="mb-6"><a href="{{ route('management.availability.index') }}" class="text-sm font-medium text-zinc-600 hover:text-zinc-950">Back to availability</a></div>
    <form method="POST" action="{{ $availability->exists ? route('management.availability.update', $availability) : route('management.availability.store') }}" class="mx-auto max-w-3xl space-y-6 rounded-lg border border-zinc-200 bg-white p-6 shadow-sm">
        @csrf
        @if ($availability->exists) @method('PUT') @endif
        <div class="grid gap-6 sm:grid-cols-2">
            <div class="sm:col-span-2"><label for="therapist_profile_id" class="block text-sm font-medium text-zinc-700">Therapist</label><select id="therapist_profile_id" name="therapist_profile_id" required class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><option value="">Select a therapist</option>@foreach ($therapists as $therapist)<option value="{{ $therapist->id }}" @selected((string) old('therapist_profile_id', $availability->therapist_profile_id) === (string) $therapist->id)>{{ trim($therapist->first_name.' '.$therapist->last_name) }}{{ $therapist->status === 'active' ? '' : ' (inactive)' }}</option>@endforeach</select>@error('therapist_profile_id') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="day_of_week" class="block text-sm font-medium text-zinc-700">Recurring weekday</label><select id="day_of_week" name="day_of_week" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><option value="">Not recurring</option>@foreach (['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'] as $value => $day)<option value="{{ $value }}" @selected((string) old('day_of_week', $availability->day_of_week) === (string) $value)>{{ $day }}</option>@endforeach</select><p class="mt-1 text-xs text-zinc-500">Choose a weekday or a specific date, not both.</p>@error('day_of_week') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="availability_date" class="block text-sm font-medium text-zinc-700">Specific date</label><input id="availability_date" name="availability_date" type="date" value="{{ old('availability_date', $availability->availability_date?->format('Y-m-d')) }}" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('availability_date') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="start_time" class="block text-sm font-medium text-zinc-700">Start time</label><input id="start_time" name="start_time" type="time" value="{{ old('start_time', $availability->start_time ? substr($availability->start_time, 0, 5) : '') }}" required class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('start_time') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="end_time" class="block text-sm font-medium text-zinc-700">End time</label><input id="end_time" name="end_time" type="time" value="{{ old('end_time', $availability->end_time ? substr($availability->end_time, 0, 5) : '') }}" required class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">@error('end_time') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div><label for="status" class="block text-sm font-medium text-zinc-700">Status</label><select id="status" name="status" required class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20"><option value="active" @selected(old('status', $availability->status ?: 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $availability->status) === 'inactive')>Inactive</option></select>@error('status') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
            <div class="sm:col-span-2"><label for="notes" class="block text-sm font-medium text-zinc-700">Notes</label><textarea id="notes" name="notes" rows="4" class="mt-2 block w-full rounded-md border border-zinc-300 px-3 py-2 focus:border-emerald-600 focus:outline-none focus:ring-2 focus:ring-emerald-600/20">{{ old('notes', $availability->notes) }}</textarea>@error('notes') <p class="mt-1 text-sm text-red-600">{{ $message }}</p> @enderror</div>
        </div>
        <div class="flex justify-end gap-3 border-t border-zinc-200 pt-5"><a href="{{ route('management.availability.index') }}" class="rounded-md border border-zinc-300 px-4 py-2 text-sm font-semibold text-zinc-700 hover:bg-zinc-50">Cancel</a><button class="rounded-md bg-emerald-700 px-4 py-2 text-sm font-semibold text-white hover:bg-emerald-800">{{ $availability->exists ? 'Save changes' : 'Create availability' }}</button></div>
    </form>
@endsection
